version: '3.9'
services:

  web:
    image: nginx
    container_name: iginx-container
    volumes:
    - ./src:/usr/share/nginx/html
    ports:
    - "8080:80"
    command: [nginx-debug, '-g', 'daemon off;']